#!/bin/bash
echo "#######################"
echo "TouchWiz Debloat Script"
echo "by GG2501YT            "
echo "#######################"
echo "Please read README.md before you continue!"
echo "Please enable ADB and connect your Phone with your Computer."
adb wait-for-device
echo "Device found!"
adb devices
echo "Debloat will start soon..."
sleep 3

## TouchWiz Apps
BLOAT=(
    "com.sec.android.gallery3d.panorama360view"
    "com.samsung.aasaservice"
    "com.samsung.android.allshare.service.fileshare"
    "com.samsung.android.allshare.service.mediashare"
    "com.sec.allsharecastplayer"
    "com.samsung.android.app.sounddetector"
    "com.sec.android.automotive.drivelinkremote"
    "com.sec.android.automotive.drivelink"
    "com.samsung.android.bbc.bbcagent"
    "com.mobeam.barcodeService"
    "com.samsung.android.beaconmanager"
    "flipboard.boxer.app"
    "flipboard.app"
    "com.sec.enterprise.knox.cloudmdm.smdms"
    "com.samsung.android.scloud.backup"
    "com.samsung.android.scloud"
    "com.sec.android.cloudagent"
    "com.samsung.android.sdk.spenv10"
    "com.sec.app.samsungprintservice"
    "com.sec.android.easyonehand"
    "com.sec.android.app.easylauncher"
    "com.sec.android.widgetapp.easymodecontactswidget"
    "com.sec.android.easysettings"
    "com.sec.esdk.elm"
    "com.sec.android.mimage.sstudio"
    "com.sec.android.mimage.photoretouching"
    "com.sec.android.widget.samsungapps"
    "com.sec.android.app.samsungapps"
    "com.samsung.android.nearby.mediaserver"
    "com.samsung.android.asksmanager"
    "com.samsung.groupcast"
    "com.sec.android.app.shealth"
    "com.sec.android.service.health"
    "com.hrs.b2c.android"
    "b2b.hrs.android.lib"
    "com.goldengekko.edsa.herold"
    "com.sec.android.app.sbrowser"
    "com.sec.kidsplat.installer"
    "com.sec.knox.foldercontainer"
    "com.samsung.knox.appsupdateagent"
    "com.sec.knox.knoxsetupwizardclient"
    "com.sec.knox.switcher"
    "com.samsung.knox.rcp.components"
    "com.samsung.klmsagent"
    "com.sec.enterprise.knox.attestation"
    "tv.peel.smartremote"
    "com.infraware.polarisviewer5"
    "com.samsung.android.sconnect"
    "com.samsung.android.personalpage.service"
    "com.samsung.android.service.travel"
    "com.vlingo.midas"
    "com.sec.android.app.billing"
    "com.sec.android.filter"
    "com.sec.android.app.SamsungContentsAgent"
    "com.sec.android.app.snsimagecache"
    "com.sec.android.app.sns3"
    "com.osp.app.signin"
    "com.sec.android.inputmethod"
    "com.samsung.android.securitylogagent"
    "com.arcsoft.magicshotstudio"
    "com.cleanmaster.sdk"
    "com.sec.android.app.storycam"
    "com.sec.android.app.tourviewer"
    "com.sec.android.widgetapp.ap.hero.accuweather"
    "com.samsung.android.app.withtv"
)

for APP in "${BLOAT[@]}"
do
    adb shell pm uninstall --user 0 "$APP"
done

## Stop ADB Connection
adb kill-server

echo "Done"
echo "Thanks for using my Debloat Scripts!"
