#!/bin/bash

adb shell pm uninstall --user 0 com.hp.android.printservice #HP Printservice
adb shell pm uninstall --user 0 com.mobilesrepublic.appy #NewsRepublic
adb shell pm uninstall --user 0 com.facebook.katana #Facebook
adb shell pm uninstall --user 0 com.facebook.orca #Messanger
adb shell pm uninstall --user 0 com.twitter.android #Twitter
adb shell pm uninstall --user 0 com.microsoft.office.word #MS Word
adb shell pm uninstall --user 0 com.microsoft.office.onenote #MS OneNote
adb shell pm uninstall --user 0 com.microsoft.office.excel #MS Excel
adb shell pm uninstall --user 0 com.dropbox.android #Dropbox
adb shell pm uninstall --user 0 com.microsoft.skydrive #OneDrive
adb shell pm uninstall --user 0 com.microsoft.office.powerpoint #MS Powerpoint
adb shell pm uninstall --user 0 com.microsoft.office.outlook #MS Outlook
adb shell pm uninstall --user 0 com.skype.raider #Skype
adb shell pm uninstall --user 0 com.microsoft.office.officehubrow #Office
adb shell pm uninstall --user 0 com.spotify.music #Spotify
adb shell pm uninstall --user 0 com.netflix.mediaclient #Netflix
