#!/bin/bash

adb shell pm uninstall --user 0 com.facebook.oxygen.installer #Facebook Installer
adb shell pm uninstall --user 0 com.facebook.oxygen.services #Facebook Services
adb shell pm uninstall --user 0 com.facebook.oxygen.appmanager #Facebook Appmanager
adb shell pm uninstall --user 0 com.facebook.oxygen.system #Facebook System
adb shell pm uninstall --user 0 com.facebook.system #Facebook System
adb shell pm uninstall --user 0 com.facebook.appmanager #Facebook Appmanager
adb shell pm uninstall --user 0 com.facebook.services #Facebook Services
adb shell pm uninstall --user 0 com.facebook.installer #Facebook Installer
