#!/bin/bash

adb shell pm uninstall --user 0 com.sec.android.gallery3d.panorama360view #Panorama360
adb shell pm uninstall --user 0 com.samsung.aasaservice #AASAService
adb shell pm uninstall --user 0 com.samsung.android.allshare.service.fileshare #AllShare
adb shell pm uninstall --user 0 com.samsung.android.allshare.service.mediashare #AllShare
adb shell pm uninstall --user 0 com.sec.allsharecastplayer #AllShare
adb shell pm uninstall --user 0 com.samsung.android.app.sounddetector #SoundDetector
adb shell pm uninstall --user 0 com.sec.android.automotive.drivelinkremote #DriveLinkRemote
adb shell pm uninstall --user 0 com.sec.android.automotive.drivelink #DriveLink
adb shell pm uninstall --user 0 com.samsung.android.bbc.bbcagent #BBCAgent
adb shell pm uninstall --user 0 com.mobeam.barcodeService #BarcodeService
adb shell pm uninstall --user 0 com.samsung.android.beaconmanager #BeaconManager
adb shell pm uninstall --user 0 flipboard.boxer.app #FlipBoard
adb shell pm uninstall --user 0 flipboard.app #FlipBoard
adb shell pm uninstall --user 0 com.sec.enterprise.knox.cloudmdm.smdms #KnoxCloudMDM
adb shell pm uninstall --user 0 com.samsung.android.scloud.backup #sCloudBackup
adb shell pm uninstall --user 0 com.samsung.android.scloud #sCloud
adb shell pm uninstall --user 0 com.sec.android.cloudagent #CouldAgent
adb shell pm uninstall --user 0 com.samsung.android.sdk.spenv10 #SPenSDK
adb shell pm uninstall --user 0 com.sec.app.samsungprintservice #SamsungPrintService
adb shell pm uninstall --user 0 com.sec.android.easyonehand #EasyOneHand
adb shell pm uninstall --user 0 com.sec.android.app.easylauncher #EasyLauncher
adb shell pm uninstall --user 0 com.sec.android.widgetapp.easymodecontactswidget #EasyModeContactsWidget
adb shell pm uninstall --user 0 com.sec.android.easysettings #EasySettings
adb shell pm uninstall --user 0 com.sec.esdk.elm #ELM
adb shell pm uninstall --user 0 com.sec.android.mimage.sstudio #MImage
adb shell pm uninstall --user 0 com.sec.android.mimage.photoretouching #MImage
adb shell pm uninstall --user 0 com.sec.android.widget.samsungapps #SamsungAppsWidget
adb shell pm uninstall --user 0 com.sec.android.app.samsungapps #SamsungApps
adb shell pm uninstall --user 0 com.samsung.android.nearby.mediaserver #NearbyMediaserver
adb shell pm uninstall --user 0 com.samsung.android.asksmanager #AsksManager
adb shell pm uninstall --user 0 com.samsung.groupcast #GroupCast
adb shell pm uninstall --user 0 com.sec.android.app.shealth #SHealthApp
adb shell pm uninstall --user 0 com.sec.android.service.health #SHealthService
adb shell pm uninstall --user 0 com.hrs.b2c.android #HRS
adb shell pm uninstall --user 0 b2b.hrs.android.lib #HRSLib
adb shell pm uninstall --user 0 com.sec.android.app.sbrowser #SamsungBrowser
adb shell pm uninstall --user 0 com.sec.kidsplat.installer #KidsInstaller
adb shell pm uninstall --user 0 com.sec.knox.foldercontainer #SecureFolder
adb shell pm uninstall --user 0 com.samsung.knox.appsupdateagent #AppsUpdateAgent
adb shell pm uninstall --user 0 com.sec.knox.knoxsetupwizardclient #KnoxSetup
adb shell pm uninstall --user 0 com.sec.knox.switcher #KnoxSwitcher
adb shell pm uninstall --user 0 com.samsung.knox.rcp.components #KnoxRCP
adb shell pm uninstall --user 0 com.samsung.klmsagent #KLMSAgent
adb shell pm uninstall --user 0 com.sec.enterprise.knox.attestation #KnoxEnterprise
adb shell pm uninstall --user 0 tv.peel.smartremote #SmartRemote
adb shell pm uninstall --user 0 com.infraware.polarisviewer5 #PolarisOffice5
adb shell pm uninstall --user 0 com.samsung.android.sconnect #Sconnect
adb shell pm uninstall --user 0 com.samsung.android.personalpage.service #PersonalPage
adb shell pm uninstall --user 0 com.samsung.android.service.travel #Travel
adb shell pm uninstall --user 0 com.vlingo.midas #SVoice
adb shell pm uninstall --user 0 com.sec.android.app.billing #Billing
adb shell pm uninstall --user 0 com.sec.android.filter #Filter
adb shell pm uninstall --user 0 com.sec.android.app.SamsungContentsAgent #SamsungContentsAgent
adb shell pm uninstall --user 0 com.sec.android.app.snsimagecache #SnsCache
adb shell pm uninstall --user 0 com.sec.android.app.sns3 #SNS
adb shell pm uninstall --user 0 com.osp.app.signin #SamsungAccountLogin
adb shell pm uninstall --user 0 com.samsung.android.securitylogagent #LogAgent
adb shell pm uninstall --user 0 com.arcsoft.magicshotstudio #MagicStudio
adb shell pm uninstall --user 0 com.cleanmaster.sdk #CMSDK
adb shell pm uninstall --user 0 com.sec.android.app.storycam #StoryCam
adb shell pm uninstall --user 0 com.sec.android.app.tourviewer #TourViewer
adb shell pm uninstall --user 0 com.sec.android.widgetapp.ap.hero.accuweather #AccuWeatherWidget
adb shell pm uninstall --user 0 com.samsung.android.app.withtv #withTV

# Userdata GApps
adb shell pm uninstall com.google.android.docs #Drive
adb shell pm uninstall com.google.android.videos #PlayVideos
adb shell pm uninstall com.google.android.photos #GooglePhotos
adb shell pm uninstall com.google.android.youtube.music #YTMusic

# Userdata Bloatware
adb shell pm uninstall com.spotify.music #Spotify
