#!/bin/bash

adb shell pm uninstall --user 0 com.sec.android.preloadinstaller #AppInstaller
adb shell pm uninstall --user 0 com.samsung.android.app.appsedge #AppsEdge
adb shell pm uninstall --user 0 com.samsung.android.visionarapps #AR-Apps
adb shell pm uninstall --user 0 com.samsung.android.ardrawing #AR-Drawing
adb shell pm uninstall --user 0 com.samsung.android.arzone #AR-Zone
adb shell pm uninstall --user 0 com.samsung.android.spdfnote #PDFNote
adb shell pm uninstall --user 0 com.sec.android.widgetapp.webmanual #WebManual
adb shell pm uninstall --user 0 com.samsung.android.motionphoto.viewer #MotionPhoto
adb shell pm uninstall --user 0 com.samsung.android.app.routines #BixbyRoutines
adb shell pm uninstall --user 0 com.samsung.android.visionintelligence #BixbyVision
adb shell pm uninstall --user 0 com.samsung.android.bixby.agent #BixbyAgent
adb shell pm uninstall --user 0 com.samsung.android.bixby.agent.dummy #BixbyAgentStub
adb shell pm uninstall --user 0 com.samsung.android.bixby.service #BixbyService
adb shell pm uninstall --user 0 com.samsung.android.bixbyvision.framework #BixbyFramework
adb shell pm uninstall --user 0 com.samsung.android.homemode #DailyBoard
adb shell pm uninstall --user 0 com.samsung.android.livestickers #LiveStickers
adb shell pm uninstall --user 0 com.samsung.android.forest #DigitalWellbeing
adb shell pm uninstall --user 0 com.samsung.android.highlightplayer #HighLightPlayer
adb shell pm uninstall --user 0 com.samsung.android.fmm #FindMyMobile
adb shell pm uninstall --user 0 com.samsung.android.app.galaxyfinder #Finder
adb shell pm uninstall --user 0 com.samsung.android.galaxy #GalaxyShop
adb shell pm uninstall com.samsung.android.galaxy
adb shell pm uninstall --user 0 com.samsung.android.themecenter #ThemeService
adb shell pm uninstall --user 0 com.samsung.android.game.gametools #GameBooster
adb shell pm uninstall --user 0 com.samsung.android.game.gamehome #GameLauncher
adb shell pm uninstall --user 0 com.samsung.android.game.gos #GameOptimizingService
adb shell pm uninstall --user 0 com.samsung.android.sm.devicesecurity #DeviceSecurity
adb shell pm uninstall --user 0 com.samsung.android.lool #DeviceManager
adb shell pm uninstall --user 0 com.hiya.service #HiyaService
adb shell pm uninstall --user 0 com.samsung.android.knox.analytics.uploader #AnalyticsUploader
adb shell pm uninstall --user 0 com.samsung.android.app.dofviewer #DOFViewer
adb shell pm uninstall --user 0 com.samsung.android.app.siofviewer #SIOFViewer
adb shell pm uninstall --user 0 com.samsung.android.service.livedrawing #LiveDrawing
adb shell pm uninstall --user 0 com.samsung.android.mdx.kit #MDEServiceFramework
adb shell pm uninstall --user 0 com.samsung.android.mdm #MDM
adb shell pm uninstall --user 0 com.samsung.android.mdx.quickboard #QuickBoard
adb shell pm uninstall --user 0 com.samsung.android.bixby.wakeup #BixbyWakeup
adb shell pm uninstall --user 0 com.samsung.android.app.social #Social
adb shell pm uninstall --user 0 com.sec.android.app.ocrservice #OCRService
adb shell pm uninstall --user 0 com.netflix.partner.activation #NetflixPartner
adb shell pm uninstall --user 0 com.sec.penup #PenUP
adb shell pm uninstall com.sec.penup
adb shell pm uninstall --user 0 com.samsung.android.knox.containercore #ContainerCore
adb shell pm uninstall --user 0 com.samsung.android.rubin.app #Rubin
adb shell pm uninstall --user 0 com.samsung.android.service.peoplestripe #People
adb shell pm uninstall --user 0 com.samsung.android.aware.service #QuickShare
adb shell pm uninstall --user 0 com.samsung.android.app.sharelive #QuickShare
adb shell pm uninstall --user 0 com.samsung.android.app.reminder #Reminder
adb shell pm uninstall --user 0 com.samsung.android.app.spage #Daily
adb shell pm uninstall --user 0 com.samsung.android.mobileservice #SamsungExperienceService
adb shell pm uninstall --user 0 com.samsung.android.galaxycontinuity #SamsungFlow
adb shell pm uninstall com.samsung.android.galaxycontinuity
adb shell pm uninstall --user 0 com.samsung.android.mateagent #MateAgent
adb shell pm uninstall --user 0 com.sec.android.app.kidshome #SamsungKids
adb shell pm uninstall --user 0 com.samsung.android.kidsinstaller #KidsInstaller
adb shell pm uninstall --user 0 com.sec.location.nsflp2 #SamsungLocationSDK
adb shell pm uninstall --user 0 com.samsung.android.voc #SamsungMembers
adb shell pm uninstall com.samsung.android.voc
adb shell pm uninstall --user 0 com.sec.android.push #PushService
adb shell pm uninstall --user 0 com.samsung.SMT #TTS
adb shell pm uninstall --user 0 com.samsung.android.svoiceime #VoiceIME
adb shell pm uninstall --user 0 com.samsung.android.app.cocktailbarservice #Cocktailbar
adb shell pm uninstall --user 0 com.samsung.android.settings.bixby #BixbySettings
adb shell pm uninstall --user 0 com.samsung.knox.securefolder #SecureFolder
adb shell pm uninstall --user 0 com.samsung.android.fast #SecureWifi
adb shell pm uninstall --user 0 com.skms.android.agent #SKMSAgent
adb shell pm uninstall --user 0 com.samsung.android.location #SamsungLocation
adb shell pm uninstall --user 0 com.sec.android.easyMover.Agent #SmartSwitchAgent
adb shell pm uninstall --user 0 com.samsung.android.smartface #SmartFace
adb shell pm uninstall --user 0 com.samsung.android.oneconnect #SmartThings
adb shell pm uninstall com.samsung.android.oneconnect
adb shell pm uninstall --user 0 com.samsung.android.stickercenter #StickerCenter
adb shell pm uninstall --user 0 com.samsung.systemui.bixby2 #SystemUIBixby2
adb shell pm uninstall --user 0 com.samsung.android.svcagent #SVCAgent
adb shell pm uninstall --user 0 com.samsung.android.icecone #KeyboardContent
adb shell pm uninstall --user 0 com.samsung.android.app.taskedge #Tasks
adb shell pm uninstall --user 0 com.samsung.android.app.tips #Tips
adb shell pm uninstall --user 0 com.sec.android.app.quicktool #Tools
adb shell pm uninstall --user 0 com.samsung.android.service.pentastic #Pentastic
adb shell pm uninstall --user 0 com.samsung.android.service.airviewdictionary #Translate
adb shell pm uninstall --user 0 de.axelspringer.yana.zeropage #upday
adb shell pm uninstall --user 0 com.samsung.android.app.watchmanagerstub #WearableInstaller
adb shell pm uninstall --user 0 com.sec.android.daemonapp #Weather
adb shell pm uninstall --user 0 com.samsung.android.net.wifi.wifiguider #Wifi-Tips
adb shell pm uninstall --user 0 com.diotek.sec.lookup.dictionary #Dictionary
adb shell pm uninstall --user 0 com.samsung.android.app.clipboardedge #ClipBoardEdge

# Userdata GApps
adb shell pm uninstall com.google.android.docs #Drive
adb shell pm uninstall com.google.android.videos #PlayVideos
adb shell pm uninstall com.google.android.photos #GooglePhotos
adb shell pm uninstall com.google.android.youtube.music #YTMusic

# Userdata Bloatware
adb shell pm uninstall com.spotify.music #Spotify
