#!/bin/bash

# EMUI 5 Parts
adb shell pm uninstall --user 0 com.huawei.android.chr #CHR Service
adb shell pm uninstall --user 0 com.huawei.phoneservice #HiCare
adb shell pm uninstall --user 0 com.huawei.iconnect #iconnect
adb shell pm uninstall --user 0 com.huawei.hwid #Huawei Account Login
adb shell pm uninstall --user 0 com.huawei.android.instantshare #Huawei Share
adb shell pm uninstall --user 0 com.huawei.indexsearch.observer #indexsearch
adb shell pm uninstall --user 0 com.huawei.indexsearch #indexsearch
adb shell pm uninstall --user 0 com.huawei.vassistant #HiVoice
adb shell pm uninstall --user 0 com.huawei.watch.sync #WatchSync
adb shell pm uninstall --user 0 com.huawei.hwstartupguide #Startup Guide
adb shell pm uninstall --user 0 com.huawei.hwaps #HwAps
adb shell pm uninstall --user 0 com.huawei.powergenie #Power Genius
adb shell pm uninstall --user 0 com.huawei.scanner #Scanner
adb shell pm uninstall --user 0 com.huawei.iaware #iAware
adb shell pm uninstall --user 0 com.huawei.mmitest #MMITest
adb shell pm uninstall --user 0 com.huawei.autoinstallapkfrommcc #Informations
adb shell pm uninstall --user 0 com.android.partnerbrowsercustomizations.tmobile #T-Mobile Browser Customizations
adb shell pm uninstall --user 0 com.huawei.trustagent #Smart unlock
adb shell pm uninstall --user 0 com.huawei.wifiprobqeservice #HwWifiproBqeService
adb shell pm uninstall com.huawei.compass #Compass
adb shell pm uninstall --user 0 com.huawei.compass
adb shell pm uninstall com.android.hwmirror #Mirror
adb shell pm uninstall --user 0 com.android.hwmirror
adb shell pm uninstall com.huawei.gamebox.global #HiGame
adb shell pm uninstall --user 0 com.huawei.gamebox.global
adb shell pm uninstall com.huawei.appmarket #AppGallery
adb shell pm uninstall --user 0 com.huawei.appmarket
adb shell pm uninstall com.huawei.health #Health
adb shell pm uninstall --user 0 com.huawei.health
adb shell pm uninstall com.huawei.KoBackup #Backup
adb shell pm uninstall --user 0 com.huawei.KoBackup

# Gameloft Games
adb shell pm uninstall com.gameloft.android.GloftAGMP
adb shell pm uninstall com.gameloft.android.GloftDBMF
adb shell pm uninstall com.gameloft.android.GloftPDMF
adb shell pm uninstall com.gameloft.android.GloftPZOR
adb shell pm uninstall com.gameloft.android.GloftSCCA
adb shell pm uninstall com.gameloft.android.GloftSCRT
adb shell pm uninstall com.gameloft.android.GloftSMIF
adb shell pm uninstall com.gameloft.android.GloftANIF
adb shell pm uninstall com.gameloft.android.GloftDMKF
adb shell pm uninstall --user 0 com.gameloft.android.GloftAGMP
adb shell pm uninstall --user 0 com.gameloft.android.GloftDBMF
adb shell pm uninstall --user 0 com.gameloft.android.GloftPDMF
adb shell pm uninstall --user 0 com.gameloft.android.GloftPZOR
adb shell pm uninstall --user 0 com.gameloft.android.GloftSCCA
adb shell pm uninstall --user 0 com.gameloft.android.GloftSCRT
adb shell pm uninstall --user 0 com.gameloft.android.GloftSMIF
adb shell pm uninstall --user 0 com.gameloft.android.GloftANIF
adb shell pm uninstall --user 0 com.gameloft.android.GloftDMKF
